function cg_coeff = CG_coeffs(ell, m, ell1, m1, ell2, m2)
cg_coeff = 0;
if m == m1 + m2 && ell + ell1 - ell2 >= 0 && ell - ell1 + ell2 >= 0 && ell1 + ell2 - ell >= 0
    sum_k = 0;
    for k=0:min([ell1 + ell2 - ell, ell1 - m1, ell2 + m2])
        if ell1 + ell2 - ell - k >= 0 && ell1 - m1 - k >= 0 && ell2 + m2 - k >= 0 && ell - ell2 + m1 + k >= 0 && ell - ell1 - m2 + k >= 0
            sum_k = sum_k + (-1)^k / (factorial(k) * factorial(ell1 + ell2 - ell - k) * factorial(ell1 - m1 - k) * factorial(ell2 + m2 - k) * factorial(ell - ell2 + m1 + k) * factorial(ell - ell1 - m2 + k));
        end
    end
    cg_coeff = sqrt( ...
        ((2 * ell + 1) * factorial(ell + ell1 - ell2) * ...
        factorial(ell - ell1 + ell2) * factorial(ell1 + ell2 - ell) * ...
        factorial(ell + m) * factorial(ell - m) * ...
        factorial(ell1 - m1) * factorial(ell1 + m1) * ...
        factorial(ell2 - m2) * factorial(ell2 + m2) ...
        ) / ...
        factorial(ell1 + ell2 + ell + 1)) * sum_k;
end
end